//
// Created by Jake Cronk on 4/17/24.
//

#ifndef ASSIGNMENT2_COURSEREGISTRATIONOUTPUTSORTED_H
#define ASSIGNMENT2_COURSEREGISTRATIONOUTPUTSORTED_H


#ifndef COURSEREGISTRATIONOUTPUTSORTED_H
#define COURSEREGISTRATIONOUTPUTSORTED_H

void createSortedCourseRegistrationOutput();

#endif // COURSEREGISTRATIONOUTPUTSORTED_H



#endif //ASSIGNMENT2_COURSEREGISTRATIONOUTPUTSORTED_H
