//
// Created by Jake Cronk on 4/17/24.
//

#ifndef ASSIGNMENT2_COURSEREGISTRATIONOUTPUT_H
#define ASSIGNMENT2_COURSEREGISTRATIONOUTPUT_H

#endif //ASSIGNMENT2_COURSEREGISTRATIONOUTPUT_H

#ifndef COURSEREGISTRATIONOUTPUT_H
#define COURSEREGISTRATIONOUTPUT_H

void createCourseRegistrationOutput();

#endif // COURSEREGISTRATIONOUTPUT_H
